development:
  adapter: postgresql
  encoding: unicode
  database: stock_development
  pool: 5
  username: J
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: stock_test
  pool: 5
  username: J
  password: password
